# Generated by Django 6.0.7 on 2026-08-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0002_alter_post_author'),
        ('profiles', '0002_profile_contact_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
